# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 13, 12, 57, 665861, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
